# Configuration file for the Sphinx documentation builder.
#
# This file contains comprehensive configuration for generating swimlib documentation
# using Sphinx with the Furo theme and advanced features.
#
# For the full list of built-in configuration values, see:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# -- Path setup --------------------------------------------------------------

# Add the parent directory to sys.path so Sphinx can find the swimlib package
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'swimlib'
copyright = f'{datetime.now().year}, Nick Spell'
author = 'Nick Spell'

# The full version, including alpha/beta/rc tags

# -- General configuration ---------------------------------------------------

extensions = [
    # Core Sphinx extensions
    'sphinx.ext.autodoc',           # Automatic documentation from docstrings
    'sphinx.ext.autosummary',       # Generate autodoc summaries
    'sphinx.ext.napoleon',          # Support for Google & NumPy style docstrings
    'sphinx.ext.intersphinx',       # Link to other project's documentation
    'sphinx.ext.viewcode',          # Add links to highlighted source code
    'sphinx.ext.githubpages',       # Publish HTML docs to GitHub Pages (creates .nojekyll)
    'sphinx.ext.todo',              # Support for todo directives

    # Third-party extensions for modern UX
    'sphinx_copybutton',            # Add copy button to code blocks
    'sphinx_inline_tabs',           # Inline tabbed content
    'myst_parser',                  # Markdown support
]

# Add any paths that contain templates here, relative to this directory
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames
source_suffix = {
    '.rst': 'restructuredtext',
    # '.md': 'markdown',  # Uncomment if using myst_parser
}

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'furo'

# Furo theme options - Modern, sleek, minimal design
html_theme_options = {
    # Sidebar configuration
    "sidebar_hide_name": False,
    "navigation_with_keys": True,

    # Light mode - Clean, professional colors
    "light_css_variables": {
        "color-brand-primary": "#0066CC",           # Professional blue
        "color-brand-content": "#0066CC",
        "color-sidebar-background": "#f8f9fa",      # Subtle gray sidebar
        "color-sidebar-background-border": "#e1e4e8",
        "font-stack": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif",
        "font-stack--monospace": "'JetBrains Mono', 'Fira Code', Consolas, Monaco, monospace",
        "font-size--normal": "16px",
        "sidebar-item-spacing-vertical": "0.5rem",  # Compact sidebar
        "toc-spacing-vertical": "0.5rem",
    },

    # Dark mode - Modern dark theme
    "dark_css_variables": {
        "color-brand-primary": "#4A9EFF",           # Lighter blue for dark
        "color-brand-content": "#4A9EFF",
        "color-sidebar-background": "#1a1d23",      # Deep dark sidebar
        "color-sidebar-background-border": "#2d3139",
        "color-background-primary": "#0d1117",      # GitHub-style dark
    },

    # Announcement banner (optional)
    # "announcement": "📦 <b>v0.1.0</b> - Production-ready automation SDK",

    # Top of page navigation
    "top_of_page_button": "edit",

    # Source code links
    "source_repository": "https://github.com/nickspell/swimlib",
    "source_branch": "master",
    "source_directory": "docs/",

    # Footer
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/nickspell/swimlib",
            "html": """
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            """,
            "class": "",
        },
    ],
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# Custom CSS files
html_css_files = [
    # 'custom.css',  # Uncomment and create if needed
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar
# html_logo = "_static/logo.png"

# The name of an image file (within the static path) to use as favicon
# html_favicon = "_static/favicon.ico"

# If true, links to the reST sources are added to the pages
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer
html_show_sphinx = False

# Output file base name for HTML help builder
htmlhelp_basename = 'swimlibdoc'

# -- Options for autodoc -----------------------------------------------------

# Autodoc settings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__',
    'show-inheritance': True,
    'inherited-members': False,
}

# Include both class docstring and __init__ docstring
autodoc_class_signature = 'separated'

# Type hints configuration
autodoc_typehints = 'description'  # Show type hints in description rather than signature
autodoc_typehints_description_target = 'documented'
autodoc_typehints_format = 'short'  # Use short form for type hints (e.g., list instead of typing.List)

# -- Options for autosummary ------------------------------------------------

autosummary_generate = True  # Automatically generate stub pages for autosummary
autosummary_imported_members = False

# -- Options for napoleon (Google/NumPy style docstrings) -------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_use_keyword = True
napoleon_custom_sections = None
napoleon_attr_annotations = True

# -- Options for intersphinx -------------------------------------------------

# Links to external documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'requests': ('https://requests.readthedocs.io/en/latest/', None),
    'paramiko': ('https://docs.paramiko.org/en/stable/', None),
    'rich': ('https://rich.readthedocs.io/en/stable/', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output
todo_include_todos = True

# -- Options for viewcode extension ------------------------------------------

viewcode_follow_imported_members = True

# -- Options for extlinks ----------------------------------------------------

# Shortened external link definitions
extlinks = {
    'issue': ('https://github.com/nickspell/swimlib/issues/%s', 'issue %s'),  # Update repo URL
    'pr': ('https://github.com/nickspell/swimlib/pull/%s', 'PR %s'),
}

# -- Options for coverage extension ------------------------------------------

coverage_show_missing_items = True

# -- Advanced configuration --------------------------------------------------

# Add any custom configuration below

# Syntax highlighting style
pygments_style = 'sphinx'
pygments_dark_style = 'monokai'

# Number figures, tables and code-blocks automatically
numfig = True
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Listing %s',
    'section': 'Section %s',
}

# Suppress warnings
suppress_warnings = [
    # 'app.add_node',
]

# Custom roles (if needed)
# rst_prolog = """
# .. role:: python(code)
#    :language: python
#    :class: highlight
# """

# rst_epilog = """
# .. |project| replace:: swimlib
# """
